version: '3.8'

services:
  # 1. Local MongoDB (Our own MongoDB instance for development)
  db:
    image: mongo:latest
    container_name: student-app-db
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  # 2. .NET Web API Backend
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: student-app-api
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      # Finalyly, we will use the MongoDB Atlas connection string for production, but you can switch to the local MongoDB connection string for development by commenting/uncommenting the lines below.
      - ConnectionStrings__DefaultConnection=mongodb+srv://supuna793_db_user:4doop6exUXH6JKRr@edusynccluster.6vex2af.mongodb.net/EduSyncDB?retryWrites=true&w=majority
    volumes:
      - ./backend:/app

  # 3. React Frontend
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: student-app-web
    ports:
      - "5173:5173"
    depends_on:
      - api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  # 4. Playwright E2E Tests
  tests:
    build:
      context: ./tests
      dockerfile: Dockerfile
    container_name: student-app-tests
    depends_on:
      - web
    environment:
      - BASE_URL=http://web:5173
    profiles:
      - testing

volumes:
  mongo_data: